# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZX2hM9PZvoAyxweEPf081lJabuI=,iv:FlsgKB/EiH/U7Lj0B+OuRhBMUck4ffl28vJ+q8x+VsI=,tag:w8XQiheLe5GdpX8BVxgNUw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:jVnoqZ89Y5pyVsVQqchhav2AuefmrO4ONxO4B7AtKhyFB/oFAQ==,iv:PKtjKV2h3y88QTte7qG7tsplcZZ5qNWokuKe4rG7Ks8=,tag:nhMmR62CSn4gPEK/Pg5mGg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:qA0GELW2iy3tM9Lq2GElYkdabw==,iv:XoCh9dsSYCne7k+rhMRUXhVgJWAC+4yMeLxSazJ6lbY=,tag:yA3bZoM3H+T/OPDdUqtYkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ys73jx248dv3q6av2mrm4tp4kt7k6sw5ys90ecf2jvhyxvxew9mq7psjj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTncrc0pZTTJYM25ZU3ZU
            WDBIN2pmNWZJK1FadGxXYjFaOVN2WUF0S0NFCmNZVFJxNlU1ZkViOFFnTUdWVGl3
            WGR4WjlUYU55Y2thNEhBZFpKRFJMK1kKLS0tIDFuOWgwcXgrZUN0Zzk3a1hGTVUr
            S0pGYk9SYi9JbUNCYkRCdzVxQmFFTzAKHckuly/3gY6yjclARobKX0bibNJJCxmJ
            ZRR5u0qLP8rkxn41T0dGXgn7x+r4pI1c+B+I1YEss9/dnVc3W2WDwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T16:33:56Z"
    mac: ENC[AES256_GCM,data:Mewqm5pc5lZ7yQXSv6SNt0KQ8xXs/SYNWe9f5GHiiqgmR8StyMawMsL5ir7QZ4EICnqhTPJmwqwan7aUOxWXLr/doqkjkiup2tW3xhUGHU5k+zGBYrL9jZcBSMT6B2u9IyUe3PuUwLwaI2Fby08sAp327rKFCJmbdUfxbZ9Z1v8=,iv:qZ3BEIfCz3AbiaifTJxYsXoqB1zHN6sKpoCgvD8du7c=,tag:hG9KUo0n+GBPVacx4zucOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
