kind: Secret
ansible_user: ENC[AES256_GCM,data:FSU0ddl9L8BYaQ==,iv:wREDEPDlk0UgHFZc1V2d7by/HCX00khe66VtY8j2MHQ=,tag:7/GDaesUmOP7AitSKGgRQw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XKermbWzssYl9Q==,iv:1coPEDwz5AnMeCpP7FDr695KRMomVe45ST/+3BgN1V0=,tag:SNHeQLB1so0XsRIFD2Mqbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ys73jx248dv3q6av2mrm4tp4kt7k6sw5ys90ecf2jvhyxvxew9mq7psjj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcDVDU3k5U25mZTQzWVFY
            cFNtTjJVeisxWGpFdkpoaXk1TmYwclJKU0RnCkVJa0daMUpoZGU5RGNuT1JRM0x4
            aXBOaTVxV3Q0Q0VpRTBXakVtTm4rdkkKLS0tIDBiNkx6V3k2MERzNDB4SjNjNVRP
            YjE0bU9nbEFyMWdZTXZRWG9PWCthY0EKN9340ApYKZkRE4Aa13vLPobVYv7k9VMK
            ePEeH8rTz0xpUGBRhxO3ZW1AIMncUiivexlbvxK0YwXcQRwOcwUEXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T16:33:56Z"
    mac: ENC[AES256_GCM,data:ItgyLmxco9y/vDlCorHhI6KqZFnPWfyfNnf/pje+czC/BaBjdKbc+nhnuqw9dA+BaliMKZ2dIa4Kg/1kKVrryV0f3pl0JpEbunuPrL4wnFzIs8xhIzgjmJ3EPlSCdcwgzc+Q1d+QJ13ufKLv8tUypHBzc0DZvSnVIVvskb8WdS4=,iv:XLZuYq3ZTcuEj7XomDUB5gS8Fz7r1/DGj1QBq7yMuJM=,tag:rUisO+Y/npiMZvSf4J6jLw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
