---
apiVersion: v1
kind: Service
metadata:
  name: novel-ai
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 6969
      targetPort: 6969
---
apiVersion: v1
kind: Endpoints
metadata:
  name: novel-ai
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.50.217
    ports:
      - port: 6969
