# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: rss-to-telegram-bot
    namespace: default
type: Opaque
stringData:
    TOKEN: ENC[AES256_GCM,data:hJp0Fcn6WwN300zk3H5JYBfp+gxRtD3B3zWrp+ck6iB84qkghF5Llqk3KZwgfA==,iv:ZMZeGj6Poa7ImzuNU81Lsu5AfbSIF/4/7UggxG6dL0A=,tag:G5vCuu04BC6/uVlJTfs0GQ==,type:str]
    MANAGER: ENC[AES256_GCM,data:DPpP/SePHb0U,iv:NSsdqrG4dNwYg9n1MVhkcJ7jrbjXH09IXgEZvhCTFPk=,tag:Xg691a9ORyWyKuYK294+QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ys73jx248dv3q6av2mrm4tp4kt7k6sw5ys90ecf2jvhyxvxew9mq7psjj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYVZUUmtGYnd5anVkbWk3
            Y2x3RnB2TG1USlhPOU1vbkd1WDRiSVVjMUF3CjZydDZwYjIyNmhsT2l0QVFUTUNJ
            LzVvMFBSVkRQS01RVmJUcFM3Y004TzQKLS0tIEJIaHNNSFlNRFBUaTJ5WWp2UDVC
            MkJpUG5rRUp1czllamtaN2s4bktZb1kKXL93MKIjMPkvnTn/oGngrAVlt3UW/R3O
            2/ilIktxehMgTKzQmPIGJMGT+IJZW6yLbdjIHeEtvD/VLKWjb0V/UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T18:56:50Z"
    mac: ENC[AES256_GCM,data:MZvXuSB2vSkG8yIRjVD11zfZlcWr6KyvQ9LxdxTsPjFkMDD4+9wvFWu0cCGDY6/529tpvlev8MpXJ0EELzUN9rbFxNnqHtdQ2aGgMAhB054Ji8zC76Ey6WK01tFpLmfy07UlNTbW0Dhohxke96XTQeXBj4muw/VzsVmEA4gIce4=,iv:O0a3iD+RafhBcAhDzB7ZasxkWXHiYjOgD2DUy3LjPMc=,tag:cs9oLGGYpnIq0SBJVs8hbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
